;;; mode-setting.el ---

;; ====================================
;; 各モードの設定
;; ====================================
(require 'generic-x)                                    ;; モードがないファイルをカラフルに

(add-hook 'after-save-hook
          'executable-make-buffer-file-executable-if-script-p) 	;; スクリプトに自動で実行権を与える

(use-package ggtags :ensure t)
(require 'ggtags)

(add-hook 'html-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (setq imenu-create-index-function 'html-imenu-create-index)
            (auto-complete-mode t)
            (require 'rename-sgml-tag)
            (gtags-mode t)
            ;;(ac-html-enable)
            ;;(ac-js2-mode)
            ;; (require 'ac-html-csswatcher)
            ;; (ac-html-csswatcher-setup)
            (smart-newline-mode t)
            (rainbow-mode)
            (rainbow-delimiters-mode)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            (add-to-list 'ac-sources 'ac-source-gtags)
            (flycheck-mode t)
            (rainbow-delimiters-mode)
            (setq tab-width 4)))

(add-hook 'nxml-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (require 'rename-sgml-tag)
            (gtags-mode t)
            (flycheck-mode t)
            (smart-newline-mode t)
            (rainbow-delimiters-mode)
            (rainbow-mode)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            (add-to-list 'ac-sources 'ac-source-gtags)
            (add-to-list 'ac-sources 'ac-source-css-property)
            (setq nxml-slash-auto-complete-flag t)
            (setq indent-tabs-mode t)
            (setq tab-width 2)))

(use-package php-mode :ensure t)
(use-package ac-php :ensure t)
(require 'php-mode)
(add-hook 'php-mode-hook
          (lambda ()
           ;;(key-combo-mode 1)
           (auto-complete-mode t)
           (require 'php-completion)
           (php-completion-mode t)
           (require 'ac-php)
           ;;(require 'phpdocumentor)
           ;; (yas-global-mode 1)
           (gtags-mode t)
           (flycheck-mode t)
           ;; (ac-html-enable)
           ;; (ac-js2-mode)
           ;; (require 'ac-html-csswatcher)
           ;; (ac-html-csswatcher-setup)
           (smart-newline-mode t)
           (rainbow-delimiters-mode)
           (rainbow-mode)
           (setq tab-width 4)
           (setq c-basic-offset 4)
           (c-set-offset 'case-label' 4)
           (c-set-offset 'arglist-intro' 4)
           (c-set-offset 'arglist-cont-nonempty' 4)
           (c-set-offset 'arglist-close' 0)
           (add-to-list 'ac-sources 'ac-source-php-completion)
           (add-to-list 'ac-sources 'ac-source-php)
           (add-to-list 'ac-sources 'ac-source-yasnippet)
           (add-to-list 'ac-sources 'ac-source-css-property)
           (add-to-list 'ac-sources 'ac-source-gtags)
))
(setq php-mode-force-pear t) ;PEAR規約のインデント設定にする

(add-hook 'js2-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (auto-complete-mode t)
            (gtags-mode t)
            (flycheck-mode t)
            ;;(ac-js2-mode)
            (smart-newline-mode t)
            (rainbow-delimiters-mode)
            (rainbow-mode)
            (add-to-list 'ac-sources 'ac-source-css-property)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            ))

(add-hook 'css-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (auto-complete-mode t)
            (gtags-mode t)
            ;;(flycheck-mode t)
            (smart-newline-mode t)
            (rainbow-delimiters-mode)
            (rainbow-mode)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            (add-to-list 'ac-sources 'ac-source-css-property)
            ))

(use-package web-mode :ensure t)
(require 'web-mode)
;;; インデント数
(add-hook 'web-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (setq web-mode-html-offset   2)
            (setq web-mode-css-offset    2)
            (setq web-mode-script-offset 2)
            (setq web-mode-php-offset    4)
            (setq web-mode-markup-indent-offset 2)
            (setq web-mode-css-indent-offset 2)
            (setq web-mode-code-indent-offset 4)
            (setq web-mode-disable-auto-pairing t)
            (setq web-mode-engines-alist
                  '(("php"    . "\\.tpl\\'"))
                  )
            (auto-complete-mode t)
            ;;(require 'ac-html)
            ;; (ac-html-enable)
            ;; (ac-js2-mode)
            (require 'php-completion)
            (php-completion-mode t)
            ;;(require 'ac-php)
            ;;(require 'phpdocumentor)
            ;; (yas-global-mode 1)
            ;; (require 'ac-html-csswatcher)
            ;; (ac-html-csswatcher-setup)
            (gtags-mode t)
            (smart-newline-mode t)
            (rainbow-delimiters-mode)
            (rainbow-mode)
            (auto-highlight-symbol-mode t)
            (setq imenu-create-index-function 'html-imenu-create-index)
            ;;(require 'rename-sgml-tag)
            (flycheck-mode t)
            (add-to-list 'ac-sources 'ac-source-php-completion)
            ;;(add-to-list 'ac-sources 'ac-source-php)
            (add-to-list 'ac-sources 'ac-source-gtags)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            (add-to-list 'ac-sources 'ac-source-css-property)
            ;; (add-to-list 'ac-sources 'ac-source-html-attribute-value)
            ;; (add-to-list 'ac-sources 'ac-source-html-tag)
            ;; (add-to-list 'ac-sources 'ac-source-html-attribute)
            ;; (add-to-list 'web-mode-ac-sources-alist
            ;;              '("html" . (ac-source-html-attribute-value
            ;;                          ac-source-html-tag
            ;;                          ac-source-html-attribute)))
            ))

(add-hook 'sql-mode-hook 'turn-on-orgstruct)

;; text-mode
(add-hook 'text-mode-hook
          (lambda ()
            ;; (key-combo-mode 1)
            (auto-complete-mode t)
            (smart-newline-mode t)
            (font-lock-mode t)
            (font-lock-fontify-buffer)
            (rainbow-mode)
            (rainbow-delimiters-mode)
           (auto-complete-mode t)))

(add-hook 'fundamental-mode-hook
          (lambda ()
            ;; (key-combo-mode 1)
            (auto-complete-mode t)
            (require 'php-completion)
            (php-completion-mode t)
            (smart-newline-mode t)
            (add-to-list 'ac-sources 'ac-source-php-completion)
            (add-to-list 'ac-sources 'ac-source-gtags)
            (add-to-list 'ac-sources 'ac-source-yasnippet)
            (add-to-list 'ac-sources 'ac-source-css-property)
           (font-lock-mode t)
           (rainbow-delimiters-mode)
           (rainbow-mode)
           (font-lock-fontify-buffer)))

(add-hook 'elisp-mode-hook
          (lambda ()
            ;; (key-combo-mode 1)
            (rainbow-delimiters-mode)
            (rainbow-mode)
            (font-lock-mode t)
            (font-lock-fontify-buffer)))

(setq auto-mode-alist
      (append (list
               ;; '("\\.c$" . c-mode)
               ;; '("\\.java$" . java-mode)
               '("\.js$" . js2-mode)
               ;; '("\\.sgm$" . sgml-mode)
               ;; '("\\.sgml$" . sgml-mode)
              ;; '("\\.html$" . sgml-mode)
             ;;  '("\\.htm$" . sgml-mode)
               '("\.xml$" . nxml-mode)
               '("\.el$" . emacs-lisp-mode)
               '("\.php$" . php-mode)
               '("\.html$" . web-mode)
               '("\.stml$" . web-mode)
               '("\.ctp$" . web-mode)
               '("\.tpl$" . web-mode)
               ;; '("\.html$" . nxml-mode)
               ;; '("\.shtml$" . nxml-mode)
               ;; '("\.ctp$" . nxml-mode)
               '("\.css$" . css-mode)
               '("\.sql$" . sql-mode)
               '("\.csv$" . csv-mode)
               '("\.txt$" . text-mode)
               '("\.md$" . markdown-mode)
               '("\.eml$" . text-mode)
               '("\.htaccess"   . apache-mode)
               '("httpd\.conf"  . apache-mode)
               '("\.org$" . org-mode)
               '("\.ini$" . ini-generic-mode)
               '("\.cnf$" . conf-mode)
               '("\.sh$"  . shell-script-mode)
               auto-mode-alist)))
